const Fighters = [
  {
    name: 'Islam Makhachev',
    nickname: '',
    rank: 1,
    wins: 27,
    losses: 1,
    division: 'Lightweight',
    isChampion: true,
    country: 'Russia',
    description:
      'Islam Makhachev is the reigning UFC Lightweight champion, known for his dominant grappling and well-rounded skill set. A protégé of Khabib Nurmagomedov, he has established himself as a formidable force in the division.',
    image: '',
  },
  {
    name: 'Alex Pereira',
    nickname: 'Poatan',
    rank: 2,
    wins: 12,
    losses: 2,
    division: 'Light Heavyweight',
    isChampion: true,
    country: 'Brazil',
    description:
      "Alex 'Poatan' Pereira is the UFC Light Heavyweight champion, renowned for his striking prowess and knockout power. Transitioning from a successful kickboxing career, he has quickly ascended the MMA ranks.",
    image: '',
  },
  {
    name: 'Jon Jones',
    nickname: 'Bones',
    rank: 3,
    wins: 27,
    losses: 1,
    division: 'Heavyweight',
    isChampion: true,
    country: 'USA',
    description:
      "Jon 'Bones' Jones is the UFC Heavyweight champion and a former Light Heavyweight champion. Known for his versatility and fight IQ, he is considered one of the greatest fighters in MMA history.",
    image: '',
  },
  {
    name: 'Ilia Topuria',
    nickname: 'El Matador',
    rank: 4,
    wins: 16,
    losses: 0,
    division: 'Featherweight',
    isChampion: true,
    country: 'Spain',
    description:
      "Ilia 'El Matador' Topuria is the undefeated UFC Featherweight champion, recognized for his dynamic striking and grappling abilities. He has rapidly risen through the ranks with impressive performances.",
    image: '',
  },
  {
    name: 'Merab Dvalishvili',
    nickname: 'The Machine',
    rank: 5,
    wins: 16,
    losses: 4,
    division: 'Bantamweight',
    isChampion: false,
    country: 'Georgia',
    description:
      "Merab 'The Machine' Dvalishvili is a top Bantamweight contender known for his relentless pace and wrestling dominance. His endurance and pressure have overwhelmed many opponents.",
    image: '',
  },
  {
    name: 'Belal Muhammad',
    nickname: 'Remember the Name',
    rank: 6,
    wins: 23,
    losses: 3,
    division: 'Welterweight',
    isChampion: false,
    country: 'USA',
    description:
      "Belal 'Remember the Name' Muhammad is a leading Welterweight contender recognized for his well-rounded skill set and strategic approach. He has consistently showcased his abilities against top-tier competition.",
    image: '',
  },
  {
    name: 'Dricus Du Plessis',
    nickname: 'Stillknocks',
    rank: 7,
    wins: 20,
    losses: 2,
    division: 'Middleweight',
    isChampion: false,
    country: 'South Africa',
    description:
      "Dricus 'Stillknocks' Du Plessis is a prominent Middleweight fighter known for his striking power and resilience. Hailing from South Africa, he has made a significant impact in the UFC.",
    image: '',
  },
  {
    name: "Sean O'Malley",
    nickname: 'Sugar',
    rank: 8,
    wins: 17,
    losses: 1,
    division: 'Bantamweight',
    isChampion: true,
    country: 'USA',
    description:
      "Sean 'Sugar' O'Malley is the UFC Bantamweight champion, celebrated for his flashy striking and charismatic persona. He has garnered a substantial following with his entertaining fighting style.",
    image: '',
  },
  {
    name: 'Leon Edwards',
    nickname: 'Rocky',
    rank: 9,
    wins: 21,
    losses: 3,
    division: 'Welterweight',
    isChampion: true,
    country: 'United Kingdom',
    description:
      "Leon 'Rocky' Edwards is the UFC Welterweight champion, known for his technical striking and composure under pressure. His journey to the title has been marked by perseverance and skill.",
    image: '',
  },
  {
    name: 'Jamahal Hill',
    nickname: 'Sweet Dreams',
    rank: 10,
    wins: 12,
    losses: 1,
    division: 'Light Heavyweight',
    isChampion: true,
    country: 'USA',
    description:
      "Jamahal 'Sweet Dreams' Hill is the UFC Light Heavyweight champion, recognized for his knockout power and striking accuracy. He has swiftly climbed the ranks with impressive finishes.",
    image: '',
  },
  {
    name: 'Israel Adesanya',
    nickname: 'The Last Stylebender',
    rank: 11,
    wins: 24,
    losses: 3,
    division: 'Middleweight',
    isChampion: false,
    country: 'Nigeria',
    description:
      "Israel 'The Last Stylebender' Adesanya is a former UFC Middleweight champion, acclaimed for his striking finesse and tactical prowess. His reign included multiple title defenses against top contenders.",
    image: '',
  },
  {
    name: 'Alexander Volkanovski',
    nickname: 'The Great',
    rank: 12,
    wins: 25,
    losses: 2,
    division: 'Featherweight',
    isChampion: false,
    country: 'Australia',
    description:
      "Alexander 'The Great' Volkanovski is a former UFC Featherweight champion, known for his well-rounded abilities and strategic fight approach. He has been involved in some of the division's most memorable bouts.",
    image: '',
  },
  {
    name: 'Max Holloway',
    nickname: 'Blessed',
    rank: 13,
    wins: 24,
    losses: 7,
    division: 'Featherweight',
    isChampion: false,
    country: 'USA',
    description:
      "Max 'Blessed' Holloway is a former UFC Featherweight champion, celebrated for his high-volume striking and durability. He remains a perennial contender in the division.",
    image: '',
  },
  {
    name: 'Kamaru Usman',
    nickname: 'The Nigerian Nightmare',
    rank: 14,
    wins: 20,
    losses: 3,
    division: 'Welterweight',
    isChampion: false,
    country: 'Nigeria',
    description:
      "Kamaru 'The Nigerian Nightmare' Usman is a former UFC Welterweight champion, known for his dominant wrestling and well-rounded skills. He held the title for several years and defended it multiple times.",
    image: '',
  },
  {
    name: 'Charles Oliveira',
    nickname: 'Do Bronx',
    rank: 15,
    wins: 34,
    losses: 9,
    division: 'Lightweight',
    isChampion: false,
    country: 'Brazil',
    description:
      "Charles 'Do Bronx' Oliveira is a former UFC Lightweight champion, known for his exceptional submission game and striking. Holding the record for most submissions in UFC history, he remains a dangerous contender in the division.",
    image: '',
  },
]
